 import { IGame } from './models/Game';
import { slugify } from './slug';

export const sampleGames: Partial<IGame>[] = [
  {
    title: "Labubu Merge",
    description: "Merge cute Labubu characters to create new and exciting combinations!",
    embedUrl: "https://html5.gamedistribution.com/f4cd70935a644d7daae05b2b4db64807/?gd_sdk_referrer_url=https://www.onlinegames.io/labubu-merge/",
    thumbnailUrl: "/images/Labubu-Merge.jpg",
    category: "puzzle",
    tags: ["labubu", "merge", "puzzle", "cute"],
    language: "en",
    featured: true,
    popularity: 95,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    title: "Labubu Doll Mukbang ASMR",
    description: "Watch Labubu enjoy delicious food in this relaxing ASMR experience!",
    embedUrl: "https://www.twoplayergames.org/gameframe/labubu-doll-mukbang-asmr?embed=1",
    thumbnailUrl: "/images/Labubu-Doll-Mukbang-Asmr.jpg",
    category: "simulation",
    tags: ["labubu", "asmr", "mukbang", "relaxing"],
    language: "en",
    featured: true,
    popularity: 88,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    title: "Labubu Merge 1",
    description: "Another version of the popular Labubu merge game!",
    embedUrl: "https://html5.gamedistribution.com/rvvASMiM/3bd8d990c6294379a7755f938a4944b4/index.html",
    thumbnailUrl: "/images/Labubu-Merge.jpg",
    category: "puzzle",
    tags: ["labubu", "merge", "puzzle", "cute"],
    language: "en",
    featured: false,
    popularity: 82,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  // Horror Games
  {
    title: "Last Seen Online",
    description: "A chilling horror game where you must survive the night and escape from unknown threats. Navigate through dark environments and solve puzzles to stay alive.",
    embedUrl: "https://kdata1.com/2023/12/last-seen-online/?key=y8&value=default",
    thumbnailUrl: "/images/last-seen-online.png",
    category: "monster",
    tags: ["horror", "survival", "escape", "dark", "thriller"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    title: "The Freak Circus",
    description: "Step into a terrifying circus where nothing is as it seems. Solve puzzles and escape from the clutches of the freak show performers in this spine-chilling adventure.",
    embedUrl: "https://html-classic.itch.zone/html/14081436/index.html",
    thumbnailUrl: "/images/The-Freak-Circus.png",
    category: "monster",
    tags: ["horror", "circus", "escape", "puzzle", "thriller"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    title: "Flesh, Blood, & Concrete",
    description: "A disturbing horror experience set in an abandoned building. Explore dark corridors and uncover the terrifying secrets hidden within the concrete walls.",
    embedUrl: "https://kdata1.com/2021/10/flesh-blood-concrete/",
    thumbnailUrl: "/images/Flesh-Blood-Concrete.png",
    category: "monster",
    tags: ["horror", "abandoned", "exploration", "dark", "mystery"],
    language: "en",
    featured: false,
    popularity: 83,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    title: "10 Minutes Till Dawn",
    description: "Survive for 10 minutes in this intense horror survival game. Fight off waves of terrifying creatures and use your wits to stay alive until dawn breaks.",
    embedUrl: "https://html-classic.itch.zone/html/5833734/10MinutesTillDawnWebGL/index.html?v=1732313710",
    thumbnailUrl: "/images/10-Minutes-Till-Dawn.png",
    category: "monster",
    tags: ["horror", "survival", "action", "intense", "dawn"],
    language: "en",
    featured: false,
    popularity: 90,
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    title: "ARSONATE",
    description: "A psychological horror game that will test your nerves. Navigate through a twisted world where reality and nightmare blend together in this disturbing experience.",
    embedUrl: "https://html-classic.itch.zone/html/14304166/ARSONATE%20-%20WEBGL_DEMO%20-%20CURRENT_RELEASE/index.html",
    thumbnailUrl: "/images/arsonate-game.png",
    category: "monster",
    tags: ["horror", "psychological", "disturbing", "nightmare", "reality"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    title: "The Anchorite",
    description: "Explore the dark chambers of an ancient monastery in this atmospheric horror game. Uncover the secrets of the anchorite and survive the supernatural threats.",
    embedUrl: "https://html-classic.itch.zone/html/12538539/index.html",
    thumbnailUrl: "/images/The-Anchorite.png",
    category: "monster",
    tags: ["horror", "monastery", "supernatural", "atmospheric", "mystery"],
    language: "en",
    featured: false,
    popularity: 86,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    title: "SYNTAXIA",
    description: "A mind-bending horror experience where code and reality collide. Solve complex puzzles and escape from a digital nightmare in this unique horror game.",
    embedUrl: "https://html-classic.itch.zone/html/12981601/index.html",
    thumbnailUrl: "/images/SYNTAXIA.png",
    category: "monster",
    tags: ["horror", "puzzle", "digital", "mind-bending", "code"],
    language: "en",
    featured: false,
    popularity: 84,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    title: "Midnight Mansion",
    description: "Explore a haunted mansion at midnight in this classic horror adventure. Solve puzzles, avoid ghosts, and uncover the dark history of the mansion.",
    embedUrl: "https://html-classic.itch.zone/html/13574890/index.html",
    thumbnailUrl: "/images/Midnight-Mansion.png",
    category: "monster",
    tags: ["horror", "mansion", "haunted", "midnight", "adventure"],
    language: "en",
    featured: false,
    popularity: 89,
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    title: "Descent",
    description: "Descend into the depths of terror in this atmospheric horror game. Navigate through dark tunnels and face your deepest fears in this chilling experience.",
    embedUrl: "https://html-classic.itch.zone/html/4990523/index.html?v=1732313735",
    thumbnailUrl: "/images/Descent.png",
    category: "monster",
    tags: ["horror", "descent", "tunnels", "atmospheric", "fear"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    title: "Teeth of Glass",
    description: "A surreal horror experience where nothing is what it seems. Navigate through a world of glass and teeth in this disturbing and beautiful horror game.",
    embedUrl: "https://html-classic.itch.zone/html/12149740/index.html",
    thumbnailUrl: "/images/Teeth-of-Glass.png",
    category: "monster",
    tags: ["horror", "surreal", "glass", "disturbing", "beautiful"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    title: "Horror Granny",
    description: "Survive the night in a house with a terrifying granny. Hide, run, and use your wits to escape from this classic horror survival game.",
    embedUrl: "https://www.miniplay.com/embed/horror-granny",
    thumbnailUrl: "/images/Horror-Granny.jpg",
    category: "monster",
    tags: ["horror", "granny", "survival", "hide", "escape"],
    language: "en",
    featured: false,
    popularity: 92,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    title: "Haunted School",
    description: "Explore a haunted school filled with supernatural entities. Solve puzzles and escape from the ghostly inhabitants in this spine-chilling adventure.",
    embedUrl: "https://games.crazygames.com/en_US/haunted-school---horror-game/index.html",
    thumbnailUrl: "/images/Horror-School-Detective-Story.png",
    category: "monster",
    tags: ["horror", "school", "haunted", "ghosts", "puzzle"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    title: "Horror Tale",
    description: "Experience a terrifying tale of horror and mystery. Navigate through dark environments and uncover the truth behind the haunting story.",
    embedUrl: "https://games.crazygames.com/en_US/haunted-school---horror-game/index.html",
    thumbnailUrl: "/images/horror-tale-3-the-witch.png",
    category: "monster",
    tags: ["horror", "tale", "mystery", "dark", "story"],
    language: "en",
    featured: false,
    popularity: 86,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    title: "911: Prey",
    description: "A terrifying emergency call horror game. Answer the phone and try to survive the night as you deal with supernatural threats and disturbing calls.",
    embedUrl: "https://games.crazygames.com/en_US/911-prey/index.html",
    thumbnailUrl: "/images/amandas-movie-night.png",
    category: "monster",
    tags: ["horror", "911", "phone", "emergency", "supernatural"],
    language: "en",
    featured: false,
    popularity: 84,
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    title: "911: Cannibal",
    description: "Another terrifying 911 horror experience. Answer emergency calls and try to survive against cannibalistic threats in this intense horror game.",
    embedUrl: "https://games.crazygames.com/en_US/911-cannibal/index.html",
    thumbnailUrl: "/images/amandas-movie-night.png",
    category: "monster",
    tags: ["horror", "911", "cannibal", "emergency", "intense"],
    language: "en",
    featured: false,
    popularity: 82,
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    title: "FNaF Shooter",
    description: "Defend yourself against animatronic threats in this Five Nights at Freddy's inspired shooter game. Use weapons to survive the night and escape the horror.",
    embedUrl: "https://games.crazygames.com/en_US/fnaf-shooter/index.html",
    thumbnailUrl: "/images/fnaf-shooter.png",
    category: "monster",
    tags: ["horror", "fnaf", "shooter", "animatronics", "survival"],
    language: "en",
    featured: false,
    popularity: 90,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    title: "Creepy Granny Scream: Scary Freddy",
    description: "Face off against both Granny and Freddy in this terrifying horror survival game. Hide, run, and survive the night against these iconic horror characters.",
    embedUrl: "https://games.crazygames.com/en_US/creepy-granny-scream-scary-freddy/index.html",
    thumbnailUrl: "/images/granny-vs-baldi-and-grandpa.png",
    category: "monster",
    tags: ["horror", "granny", "freddy", "scream", "survival"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    title: "C-Virus Game: Outbreak",
    description: "Survive a viral outbreak in this intense horror survival game. Fight off infected creatures and try to escape the contaminated area before it's too late.",
    embedUrl: "https://games.crazygames.com/en_US/c-virus-game-outbreak/index.html",
    thumbnailUrl: "/images/sprunki-infected.png",
    category: "monster",
    tags: ["horror", "virus", "outbreak", "survival", "infected"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    title: "House of Celestina",
    description: "Explore the mysterious House of Celestina in this atmospheric horror adventure. Uncover dark secrets and survive the supernatural threats within.",
    embedUrl: "https://games.crazygames.com/en_US/house-of-celestina/index.html",
    thumbnailUrl: "/images/House-of-Celestina.png",
    category: "monster",
    tags: ["horror", "house", "celestina", "mystery", "supernatural"],
    language: "en",
    featured: false,
    popularity: 83,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    title: "Silent House",
    description: "Enter a house where silence speaks volumes. Navigate through the eerie silence and uncover the dark secrets hidden within the walls.",
    embedUrl: "https://games.crazygames.com/en_US/silent-house/index.html",
    thumbnailUrl: "/images/silent-asylun.png",
    category: "monster",
    tags: ["horror", "silent", "house", "eerie", "secrets"],
    language: "en",
    featured: false,
    popularity: 81,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    title: "Ann",
    description: "Meet Ann, a mysterious and terrifying entity in this psychological horror game. Navigate through her twisted world and try to survive the encounter.",
    embedUrl: "https://games.crazygames.com/en_US/ann/index.html",
    thumbnailUrl: "/images/amandas-movie-night.png",
    category: "monster",
    tags: ["horror", "ann", "psychological", "entity", "twisted"],
    language: "en",
    featured: false,
    popularity: 79,
    createdAt: new Date('2023-12-31'),
    updatedAt: new Date('2023-12-31'),
  },
  // More Horror Games from Horror-Games.txt
  {
    title: "Alice is Dead 2",
    description: "Continue Alice's nightmarish journey in this sequel to the classic horror adventure. Navigate through twisted environments and solve puzzles to survive.",
    embedUrl: "https://horrorgames.io/alice-is-dead-2.embed",
    thumbnailUrl: "/images/Alice-is-Dead-2.png",
    category: "monster",
    tags: ["horror", "alice", "adventure", "nightmare", "puzzle"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2023-12-30'),
    updatedAt: new Date('2023-12-30'),
  },
  {
    title: "5 Nights with Labubu: Survival",
    description: "Survive five terrifying nights with Labubu in this horror survival game. Use your wits and resources to make it through each night.",
    embedUrl: "https://horrorgames.io/5-nights-with-labubu-survival.embed",
    thumbnailUrl: "/images/5-Nights-with-Labubu-Survival.png",
    category: "monster",
    tags: ["horror", "labubu", "survival", "nights", "scary"],
    language: "en",
    featured: false,
    popularity: 92,
    createdAt: new Date('2023-12-29'),
    updatedAt: new Date('2023-12-29'),
  },
  {
    title: "Doppelpartment",
    description: "Explore a mysterious apartment building where reality and nightmare blend together. Solve puzzles and uncover the dark secrets within.",
    embedUrl: "https://horrorgames.io/doppelpartment.embed",
    thumbnailUrl: "/images/Doppelpartment.png",
    category: "monster",
    tags: ["horror", "apartment", "mystery", "nightmare", "puzzle"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2023-12-28'),
    updatedAt: new Date('2023-12-28'),
  },
  {
    title: "Victor's Nightmares",
    description: "Enter Victor's twisted nightmares in this psychological horror experience. Navigate through surreal environments and face your deepest fears.",
    embedUrl: "https://horrorgames.io/victors-nightmares.embed",
    thumbnailUrl: "/images/Victor's-Nightmares.png",
    category: "monster",
    tags: ["horror", "victor", "nightmares", "psychological", "surreal"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2023-12-27'),
    updatedAt: new Date('2023-12-27'),
  },
  {
    title: "Cowboys vs Vampires",
    description: "A unique horror action game where cowboys face off against vampire threats. Use your weapons and skills to survive the supernatural showdown.",
    embedUrl: "https://horrorgames.io/cowboys-vs-vampires.embed",
    thumbnailUrl: "/images/Cowboys-vs-Vampires.png",
    category: "monster",
    tags: ["horror", "cowboys", "vampires", "action", "supernatural"],
    language: "en",
    featured: false,
    popularity: 89,
    createdAt: new Date('2023-12-26'),
    updatedAt: new Date('2023-12-26'),
  },
  {
    title: "Hood Episode 3",
    description: "Continue the Hood series in this third installment of the horror adventure. Face new threats and uncover more dark secrets.",
    embedUrl: "https://horrorgames.io/hood-episode-3.embed",
    thumbnailUrl: "/images/Hood-Episode-3.png",
    category: "monster",
    tags: ["horror", "hood", "episode", "adventure", "secrets"],
    language: "en",
    featured: false,
    popularity: 86,
    createdAt: new Date('2023-12-25'),
    updatedAt: new Date('2023-12-25'),
  },
  {
    title: "Alice is Dead 3",
    description: "The final chapter in Alice's horror trilogy. Face the ultimate nightmare and try to escape from the twisted world once and for all.",
    embedUrl: "https://horrorgames.io/alice-is-dead-3.embed",
    thumbnailUrl: "/images/Alice-is-Dead-3.png",
    category: "monster",
    tags: ["horror", "alice", "final", "nightmare", "escape"],
    language: "en",
    featured: false,
    popularity: 90,
    createdAt: new Date('2023-12-24'),
    updatedAt: new Date('2023-12-24'),
  },
  {
    title: "Storm the Swan",
    description: "A dark and atmospheric horror game set in a mysterious swan-themed environment. Navigate through the storm and uncover the truth.",
    embedUrl: "https://horrorgames.io/storm-the-swan.embed",
    thumbnailUrl: "/images/Storm-the-Swan.png",
    category: "monster",
    tags: ["horror", "swan", "storm", "atmospheric", "mystery"],
    language: "en",
    featured: false,
    popularity: 84,
    createdAt: new Date('2023-12-23'),
    updatedAt: new Date('2023-12-23'),
  },
  {
    title: "The Second Sight: Dead Reckoning",
    description: "Use your supernatural abilities to navigate through a haunted environment in this psychic horror adventure.",
    embedUrl: "https://horrorgames.io/the-second-sight-dead-reckoning.embed",
    thumbnailUrl: "/images/The-Second-Sight-Dead-Reckoning.png",
    category: "monster",
    tags: ["horror", "psychic", "supernatural", "haunted", "abilities"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2023-12-22'),
    updatedAt: new Date('2023-12-22'),
  },
  {
    title: "Doors Castle",
    description: "Explore a mysterious castle filled with doors that lead to different dimensions. Solve puzzles and survive the supernatural threats within.",
    embedUrl: "https://horrorgames.io/doors-castle.embed",
    thumbnailUrl: "/images/Doors-Castle.png",
    category: "monster",
    tags: ["horror", "doors", "castle", "dimensions", "puzzle"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2023-12-21'),
    updatedAt: new Date('2023-12-21'),
  },
  {
    title: "Stray Souls: Dollhouse Story",
    description: "A haunting tale set in a mysterious dollhouse. Navigate through the eerie environment and uncover the dark story behind the dolls.",
    embedUrl: "https://horrorgames.io/stray-souls-dollhouse-story.embed",
    thumbnailUrl: "/images/stray-souls-dollhouse.png",
    category: "monster",
    tags: ["horror", "dollhouse", "dolls", "haunting", "story"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date('2023-12-20'),
  },
  {
    title: "Horror School Detective Story",
    description: "Play as a detective investigating supernatural events at a haunted school. Solve mysteries and uncover the truth behind the horror.",
    embedUrl: "https://horrorgames.io/horror-school-detective-story.embed",
    thumbnailUrl: "/images/horror-school-detective.png",
    category: "monster",
    tags: ["horror", "school", "detective", "supernatural", "mystery"],
    language: "en",
    featured: false,
    popularity: 89,
    createdAt: new Date('2023-12-19'),
    updatedAt: new Date('2023-12-19'),
  },
  {
    title: "Bloodborne Kart",
    description: "A unique horror racing game inspired by Bloodborne. Race through dark environments while avoiding terrifying creatures and obstacles.",
    embedUrl: "https://horrorgames.io/bloodborne-kart.embed",
    thumbnailUrl: "/images/Bloodborne-Kart.png",
    category: "monster",
    tags: ["horror", "bloodborne", "racing", "dark", "creatures"],
    language: "en",
    featured: false,
    popularity: 91,
    createdAt: new Date('2023-12-18'),
    updatedAt: new Date('2023-12-18'),
  },
  {
    title: "Julia was Alone (Chapter 2)",
    description: "Continue Julia's lonely journey in this second chapter of the horror adventure. Face new challenges and uncover more of the dark story.",
    embedUrl: "https://horrorgames.io/julia-was-alone-chaper-2.embed",
    thumbnailUrl: "/images/Julia-was-Alone-Chaper 2.png",
    category: "monster",
    tags: ["horror", "julia", "alone", "chapter", "journey"],
    language: "en",
    featured: false,
    popularity: 86,
    createdAt: new Date('2023-12-17'),
    updatedAt: new Date('2023-12-17'),
  },
  {
    title: "Necromancer's Book",
    description: "Dive into the dark world of necromancy in this atmospheric horror game. Use forbidden knowledge to survive and uncover ancient secrets.",
    embedUrl: "https://horrorgames.io/necromancers-book.embed",
    thumbnailUrl: "/images/necromancers-book.png",
    category: "monster",
    tags: ["horror", "necromancer", "book", "dark", "forbidden"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2023-12-16'),
    updatedAt: new Date('2023-12-16'),
  },
  {
    title: "Grim Weeper 0.4",
    description: "A dark and twisted horror experience where you must navigate through a world of sorrow and despair. Face your inner demons and try to survive.",
    embedUrl: "https://horrorgames.io/grim-weeper-04.embed",
    thumbnailUrl: "/images/Grim-Weeper-0.4.png",
    category: "monster",
    tags: ["horror", "grim", "weeper", "sorrow", "despair"],
    language: "en",
    featured: false,
    popularity: 84,
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2023-12-15'),
  },
  {
    title: "Hood Episode 2",
    description: "Continue the Hood series in this second installment. Face new horrors and uncover more secrets in this ongoing horror adventure.",
    embedUrl: "https://horrorgames.io/hood-episode-2.embed",
    thumbnailUrl: "/images/hood-episode-2.png",
    category: "monster",
    tags: ["horror", "hood", "episode", "horrors", "secrets"],
    language: "en",
    featured: false,
    popularity: 87,
    createdAt: new Date('2023-12-14'),
    updatedAt: new Date('2023-12-14'),
  },
  {
    title: "Creepy Cave Cave-In",
    description: "Survive a cave-in in this intense horror survival game. Navigate through the dark caves and try to escape before it's too late.",
    embedUrl: "https://horrorgames.io/creepy-cave-cave-in.embed",
    thumbnailUrl: "/images/creepy-cave-cave-in.png",
    category: "monster",
    tags: ["horror", "cave", "cave-in", "survival", "escape"],
    language: "en",
    featured: false,
    popularity: 85,
    createdAt: new Date('2023-12-13'),
    updatedAt: new Date('2023-12-13'),
  },
  {
    title: "Earn To Die",
    description: "A unique horror survival game where you must earn money to survive. Make difficult choices and try to stay alive in this dark world.",
    embedUrl: "https://horrorgames.io/earn-to-die.embed",
    thumbnailUrl: "/images/earn-to-die.png",
    category: "monster",
    tags: ["horror", "earn", "die", "survival", "money"],
    language: "en",
    featured: false,
    popularity: 83,
    createdAt: new Date('2023-12-12'),
    updatedAt: new Date('2023-12-12'),
  },
  {
    title: "Let Sleeping Dogs Lie",
    description: "A psychological horror game about disturbing the peace. Navigate through a world where waking up sleeping dogs leads to terrifying consequences.",
    embedUrl: "https://horrorgames.io/let-sleeping-dogs-lie.embed",
    thumbnailUrl: "/images/let-sleeping-dogs-lie.png",
    category: "monster",
    tags: ["horror", "sleeping", "dogs", "psychological", "consequences"],
    language: "en",
    featured: false,
    popularity: 86,
    createdAt: new Date('2023-12-11'),
    updatedAt: new Date('2023-12-11'),
  },
  {
    title: "Twilight Watcher",
    description: "Watch over the twilight hours in this atmospheric horror game. Navigate through the liminal space between day and night where horrors lurk.",
    embedUrl: "https://horrorgames.io/twiligh-watcher.embed",
    thumbnailUrl: "/images/twilight-watcher.png",
    category: "monster",
    tags: ["horror", "twilight", "watcher", "atmospheric", "liminal"],
    language: "en",
    featured: false,
    popularity: 88,
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2023-12-10'),
  },
];

// Normalize IDs to stable slugs so routing never 404s due to duplicates/special chars
for (const game of sampleGames) {
  if (!game._id) {
    (game as { _id?: string })._id = slugify(game.title || '');
  }
}

// 获取特色游戏
export function getFeaturedGames(): Partial<IGame>[] {
  return sampleGames.filter(game => game.featured);
}

// 获取新游戏
export function getNewGames(): Partial<IGame>[] {
  return sampleGames.slice(0, 6);
}

// 根据分类获取游戏
export function getGamesByCategory(category: string): Partial<IGame>[] {
  return sampleGames.filter(game => game.category === category);
}

// 根据网络速度选择游戏
interface NetworkConnection {
  effectiveType: string;
}

export function getGamesByNetworkSpeed(): Partial<IGame>[] {
  // 检查是否在浏览器环境中
  if (typeof window === 'undefined') {
    return sampleGames;
  }
  
  const connection = (navigator as unknown as { connection?: NetworkConnection }).connection;
  if (connection) {
    const effectiveType = connection.effectiveType;
    if (effectiveType === 'slow-2g' || effectiveType === '2g') {
      return sampleGames.filter(game => {
        const gameWithLoadTime = game as IGame & { loadTime?: number };
        return gameWithLoadTime.loadTime && gameWithLoadTime.loadTime <= 5;
      });
    }
  }
  return sampleGames;
}

// 搜索游戏
export function searchGames(query: string): Partial<IGame>[] {
  const lowercaseQuery = query.toLowerCase();
  return sampleGames.filter(game => 
    game.title?.toLowerCase().includes(lowercaseQuery) ||
    game.description?.toLowerCase().includes(lowercaseQuery) ||
    game.tags?.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
}